academy/academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing/', include(('landing.urls', 'landing'), namespace='landing'))
]

urlpatterns += staticfiles_urlpatterns()

academy/landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path(route, view.name, url_name)
    # route - строка которая содержит url. Именно с ней маршрутизатор сапоставляет url с запроса
    # view - функция определённого route. Будет автоматически запущена если какойто из route подошел с url запроса
    # url_name - имя нашего route который необходимо использовать при создании ссылки, вместо указывания полного пути
    path('home/', views.home, name='home'),
    path('greeting/', views.greeting, name='greeting'),
    # создаём юрл 'course/<int:pk>' где pk - это уникальный идентификатор
    # важно чтобы параметр функции назывался точно так же как и в urls.py
    path('course/<int:pk>', views.course, name='course'),
    path('check_leads/', views.check_leads, name='check_leads'),
]

academy/landing/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    duration = models.IntegerField()

    def __str__(self):
        return self.title


class Teacher(models.Model):
    full_name = models.CharField(max_length=255)
    teaching_course = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name


class Lead(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.last_name} ({self.phone_number})"

# ForeignKey - тип поля один - к - одному
# Это поле необходимо для создания связи какого либо поля с другой моделью

# null - необходим для определения обязательности внесения информации в поле

# есть 3 сценария действий бд после удаления какой либо модели с которой налажена связь
# 1) если модель удалена, то будет удалён и столбец, который ссылался на эту модель - models.CASCADE
# 2)  если мод удалена, то поля столбца примут значения null - models.SET_NULL
# 3) если мод удалена, то значения полей сохранятся - models.PROTECT

academy/landing/forms.py
from django import forms
from .models import Lead


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead  # связка формы с моделью Lead
        fields = ['name', 'last_name', 'phone_number']  # перечисление необходимых полей

academy/landing/views.py
from django.shortcuts import render
from .models import *
from .forms import LeadForm


# любой вид (функция) принемает первым атрибутом request
# а иначе запрос
# ибо интернет работает на принцепе requesr - response

def home(request):
    courses = Course.objects.all()
    teachers = Teacher.objects.all()
    return render(request, 'home.html', {'courses': courses, 'teachers': teachers})


def greeting(request):
    teachers = Teacher.objects.all()
    return render(request, 'greeting.html', {'teachers': teachers})


def course(request, pk):
    # запрос на получение определённого обьекта
    course_data = Course.objects.get(pk=pk)
    form = LeadForm(request.POST or None)
    is_success = False
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        # commit=False - приостановка сохранения данных идущих с формы в бд
        is_success = True
        instance.course = course_data
        instance.save()
        form = LeadForm()
    return render(request, 'course.html', {'course': course_data, 'form': form, 'is_success': is_success})


def check_leads(request):
    leads = Lead.objects.all()
    return render(
        request,
        'leads.html',
        {'leads': leads}
    )

academy/landing/templates/base_layout.html
{% load static from static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link type="image/x-icon" href="https://www.svgrepo.com/show/353657/django-icon.svg" rel="icon">
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<section class="hero is-success is-fullheight">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item">
                        <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item is-active" href="{% url 'landing:home' %}">
                            Home
                        </a>
                        <a class="navbar-item" href="{% url 'landing:greeting' %}">
                            Greeting
                        </a>
                        {% if request.user.is_superuser %}
                            <a class="navbar-item" href="{% url 'landing:check_leads' %}">
                                Просмтреть заявки
                            </a>
                        {% endif %}
                        <span class="navbar-item">
                                <a class="button is-success is-inverted">
                                    <span class="icon">
                                        <i class="fab fa-github"></i>
                                    </span>
                                    <span>Download</span>
                                </a>
                            </span>
                    </div>
                </div>
            </div>
        </header>
    </div>

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <img src="{% static 'images/comp.svg' %}" width="100%" alt="">
                </div>
                <div class="column is-5-desktop is-offset-1-desktop">
                    <div class="title is-1">Lorem ipsum dolor sit amet.</div>
                    <div class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur,
                        minima!
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Hero footer: will stick at the bottom -->

</section>
{% block content %}
{% endblock %}
<footer class="section has-background-success">
    <div class="container">
        <div class="columns">
            <div class="column is-flex is-justify-content-center is-align-items-center">
                <figure class="image" style="width: 100px">
                    <img src="https://bulma.io/images/bulma-type-white.png" alt="">
                </figure>
            </div>
            <div class="column">
                <ul>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                </ul>
            </div>
            <div class="column">
                <ul>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                </ul>
            </div>
            <div class="column">
                <ul>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                </ul>
            </div>
            <div class="column">
                <ul>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                    <li class="subtitle has-text-white">lorem, ipsum.</li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</body>

</html>

academy/landing/templates/course.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <section id="topics" class="section is-medium grey-bg">
        <div class="container">
            <div class="has-text-centered">
                <h2 class="title"><span class="has-text-info">Подробнее</span> о курсе {{ course }}</h2>
                <p class="subtitle">Наше обучение длится <b>{{ course.duration }}</b> месяцев,
                    большую часть из которых Вы будете изучать материал на практике, а последний месяц у Вас будет в
                    формате
                    выпускного проекта, который вы будете разрабатывать в команде. Уроки ведутся 3 раза в неделю через
                    день.</p>
                <p class="subtitle">Стоимость курса <b>{{ course.price }}</b> сум. Оплата ежемесячная.</p><br>
            </div>
            <div class="columns is-vcentered topic">
                <div class="column is-5">
                    <img src="https://www.svgrepo.com/show/197801/lesson.svg" alt="">
                </div>
                <div class="column is-offset-1">
                    <h1 class="title is-3 has-text-info">
                        Описание курса
                    </h1><br>
                    <h2 class="subtitle">{{ course.description }}</h2>
                </div>
            </div>
        </div>
    </section>
    <section id="join" class="section is-medium grey-bg">
        {#        {% if is_success %}#}
        {#            <div class="modal">#}
        {#                <div class="modal-background"></div>#}
        {#                <div class="modal-content">#}
        {#                    <div class="title has-text-success">#}
        {#                        Ваша заявка принята. Спасибо!#}
        {#                        <button class="redirect"> Переидти на главную страницу </button>#}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        {% endif %}#}
        <div class="container">
            <div class="has-text-centered">
                <h1 class="title is-1">Запишитесь к нам на курсы</h1>
                <h2 class="subtitle has-text-grey">
                    Время стать лучше, запишитесь к нам на курсы прямо сейчас
                </h2>
            </div>
            <br><br><br>
            <div class="columns is-variable is-8 is-vcentered">
                <div class="column">
                    <img src="{% static 'images/join.svg' %}" alt="Join illustration">
                </div>

                <div class="column">
                    <div class="box">
                        {% if is_success %}
                            <div class="title has-text-info">
                                Ваша заявка принята. Спасибо!
                                <a href="" class="button is-link is-ghost is-fullwidth">
                                    Оставить ещё одну заявку
                                </a>
                            </div>
                        {% else %}
                            <form method="post" class="form">
                                {% csrf_token %}
                                {{ form }}
                                <button type="submit" class="button is-primary is-fullwidth">Отправить</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}


academy/landing/templates/greeting.html
{% extends 'base_layout.html' %}
{% load static from static %}


{% block content %}
    <section class="section is-medium has-background-success">
        <div class="container"">
            <div class="container has-text-centered">
                <p class="title">
                    Здравствуйте, уважаемый пользователь
                </p>
                <p class="subtitle">
                    Наши преподаватели
                </p>
                <div class="columns">
                    {% for teacher in teachers %}
                        <div class="column">
                            <div class="box">
                                <figur class="image">
                                    <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png"
                                         alt="">
                                </figur>
                                <br>
                                <div class="title is-4 has-text-black">{{ teacher }}</div>
                                <div class="content has-text-black">{{ teacher.teaching_course }}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

academy/landing/templates/home.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <section class="section is-medium has-background-success">
        <div class="container">
            <div class="title is-2 has-text-centered is-capitalized">
                наши курсы
            </div>
            <div class="columns">
                {% for cours in courses %}
                    <div class="column">
                        <a href="{% url 'landing:course' cours.pk %}">
                            <div class="box has-text-centered">
                                <figur class="image">
                                    <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png"
                                         alt="">
                                </figur>
                                <br>
                                <div class="title is-4 has-text-black mt-6">{{ cours }}</div>
                                <br>
                                <div class="subtitle is-spaced has-text-black">{{ cours.price }} рублей</div>
                                <div class="content has-text-black">{{ cours.duration }} месяцев</div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

academy/landing/templates/leads.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
    <section class="section is-medium has-background-success">
        <div class="container">
            <div class="columns is-multiline is-centered">
                {% for lead in leads %}
                    <div class="column">
                        <div class="box has-text-centered">
                            <div class="subtitle is-spaced has-text-black">
                                <div class="title is-4 has-text-black mt-6">Имя</div>
                                {{ lead.name }} <br> {{ lead.last_name }}
                            </div>
                            <div class="subtitle is-spaced has-text-black">
                                <div class="title is-4 has-text-black mt-6">Телефон</div>
                                {{ lead.phone_number }}
                            </div>
                            <div class="subtitle is-spaced has-text-black">
                                <div class="title is-4 has-text-black mt-6">Курс</div>
                                {{ lead.course }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}